### ISSUE TITLE
FFI and uncaught exception when parsing invalid SMILES

### ISSUE THREAD

**Issue by rapodaca** [epam/Indigo#42]
I'm trying to use the Indigo API through ffi on OS X:

https://en.wikipedia.org/wiki/Foreign_function_interface

My target language is JavaScript (nodejs 5.6.0), and I'm using the node-ffi package.

I define my interface like this:

``` javascript
var libpath = './libindigo.dylib'
var lib = ffi.Library(indigoPath, {
  'indigoLoadMoleculeFromString': ['uint64', ['string']]
};
```

Loading a valid SMILES works fine:

``` javascript
var mol = lib.indigoLoadMoleculeFromString('c1ccccc1');
```

However, the node process exits when loading an invalid SMILES:

``` javascript
var mol = lib.indigoLoadMoleculeFromString('foobar');
```

> libc++abi.dylib: terminating with uncaught exception of type indigo::SmilesLoader::Error
> Abort trap: 6

So far I haven't found a way for node-ffi to catch errors thrown by a native library to allow them to be processed by the JavaScript interpreter.

Given that apparent limitation, is it possible to prevent Indigo from throwing errors in the first place? I though that's what the return value mechanism defined in <code>indigo.h</code> was for.

**Comment by AlexanderSavelyev** [comment]
The Indigo c-interface does not throw exceptions. There is a wrapper for each and every indigoXXX() method which catches ALL exceptions internally. My guess is that there is some parameter in node-ffi which prevents exceptions to be throw. Indigo-core is written in C++ with exceptions, but C-interface does not throw any. 
By quick googling I found this thread

https://github.com/nodejs/node-gyp/issues/17

Don't know if it is related, but Indigo libraries are used in JNI and python ctypes wrappers without issues (also FFI interface)

Also want to give here some notes about the errors in c-inteface. indigoGetLastError() should be used. 

```
        unsigned long long id = indigoAllocSessionId();
	indigoSetSessionId(id);

        int mol = indigoLoadMolecule("foobar");

        if (mol < 0) {
            printf("%s", indigoGetLastError();
        }
        //Optional. Free object
        indigoFree(mol);
        //Free session
        indigoReleaseSessionId(id);
```

Please take a look for example on Java wrapper above c-interface 
https://github.com/epam/Indigo/tree/master/api/java/src/main/java/com/epam/indigo

**Comment by AlexanderSavelyev** [comment]
Another comment about the code
```
'indigoLoadMoleculeFromString': ['uint64', ['string']]
```
indigoLoadMoleculeFromString returns **int** but not **uint64**

**Comment by AlexanderSavelyev** [comment]
I think the issue reason is within build flags for Xcode project in cmake. Very similar problem was found and resolved here

https://github.com/joeferner/node-oracle/issues/148

For OSX the flag **GCC_ENABLE_CPP_EXCEPTION** should be set **YES**

**Comment by kolya-ay** [comment]
@rapodaca FYI, we are currently working on official nodejs indigo bindings. The development is a bit stalled for now in "alpha" stage. However we hope to release it to github in a couple of month.

**Comment by rapodaca** [comment]
Thanks for the tips. The node-ffi package already sets the GCC_ENABLE_CPP_EXCEPTION flag to YES:

https://github.com/node-ffi/node-ffi/blob/master/binding.gyp#L24

For good measure, I also set this, after following up on the thread you linked to:

'GCC_ENABLE_CPP_RTTI': 'YES'

Recompiling node-ffi and using the modified ffi module does not resolve the problem. Nor does changing the return type from 'uint64' to 'int' in my library.

It's good to know the Node.js binding are underway. Unfortunately, the simplest way to use Indigo from Node at the moment (on OSX at least) doesn't seem to reliably.

**Comment by AlexanderSavelyev** [comment]
I think the question still open. I' not a specialist in node but from the node-ffi docs I found that node-gyp is used to compile from sources (create dylib from C++ code). In our case we compile dylib library using cmake + Xcode
My optimistic suggestion is that this issue can be resolved by adding the mentioned GCC flag (in one of cmake configuration files) and re-compiling the library for OSX.
In pessimistic case, we should recompile the library using node-gyp - which will be much harder - because there are lot of dependencies in the code.

**Comment by rapodaca** [comment]
>My optimistic suggestion is that this issue can be resolved by adding the mentioned GCC flag (in one of cmake configuration files) and re-compiling the library for OSX.

What would the be the best way to do this? I have limited experience with cmake.

**Comment by rapodaca** [comment]
Here's how I resolved the issue:

1. Download Xcode5.1.1.dmg from Apple: https://developer.apple.com/downloads/?name=Xcode
2. Open the dmg.
3. Install the 10.8 SDK with the command:

```
sudo cp -a /Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
```

Then, compile with:

```
$ python build_scripts/indigo-release-libs.py --preset=mac10.8
```

**Comment by AlexanderSavelyev** [comment]
@rapodaca glad to hear that the issue is resolved. But we want to make sure what was the reason? Could you inform us:
1. libindigo.dylib which you mentioned - where it was taken from? Did it was compiled
2. What version of Xcode was used before the version specified 5.1.1? BTW We use 7.2.1 to compile our binaries for Indigo.
3. What SDK was used before?
4. (Recompiling node-ffi ) - do you recompile node-ffi every time and what version of Xcode, SDK do you use for that?

It will be very helpful to understand the initial issue here.

**Comment by rapodaca** [comment]
>  libindigo.dylib which you mentioned - where it was taken from? Was it compiled

Yes, compiled from badcc2b5a69bbef56439c0cf47afcfd90c1ed2e5

> What version of Xcode was used before the version specified 5.1.1? BTW We use 7.2.1 to compile our binaries for Indigo.

I'm not sure. The SDK version seems to be the most important thing.

> What SDK was used before?

10.11

> (Recompiling node-ffi ) - do you recompile node-ffi every time and what version of Xcode, SDK do you use for that?

I didn't need to recompile node-ffi to get this working. Simple recompile Indigo using the 10.8 preset (after installing the 10.8 SDK).

In summary, I believe the issue was that the 10.11 SDK, for whatever reason, doesn't propagate exceptions the same way as 10.8. It may be that 10.10 would also work. I didn't try any other SDK version.

**Comment by mkviatkovskii** [comment]
Dear @derzhavets-emg, could you please provide a minimal example that raises such uncatchable exception?

**Comment by derzhavets-emg** [comment]
Hi @mkviatkovskii 

I apologize, it probably was not a correct place to submit an issue. My issue is with node-ffi in general, that node doesn't catch DLL exceptions. It is not related to Indigo.

I assume you may re-close the issue :)
